/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ISAIAH SHELL
 */
public class Number_to_words extends javax.swing.JFrame {

    /**
     *
     *
     * Creates new form Number_to_words
     */
    public Number_to_words() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        enterbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        numberInput = new javax.swing.JTextField();
        cancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setBackground(new java.awt.Color(51, 51, 255));
        body.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bodyclick(evt);
            }
        });

        output.setBackground(new java.awt.Color(51, 51, 255));
        output.setColumns(20);
        output.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        output.setForeground(new java.awt.Color(0, 0, 0));
        output.setLineWrap(true);
        output.setRows(5);
        output.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outputclick(evt);
            }
        });
        jScrollPane1.setViewportView(output);

        enterbutton.setBackground(new java.awt.Color(255, 0, 0));
        enterbutton.setFont(new java.awt.Font("Leelawadee", 3, 18)); // NOI18N
        enterbutton.setForeground(new java.awt.Color(51, 51, 255));
        enterbutton.setText("ENTER");
        enterbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Console", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("NUMBER TO WORDS");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        numberInput.setBackground(new java.awt.Color(102, 102, 255));
        numberInput.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        numberInput.setForeground(new java.awt.Color(0, 0, 0));
        numberInput.setText("Enter a number");
        numberInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear1(evt);
            }
        });
        numberInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clear(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(102, 102, 255));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 0, 0));
        cancel.setText("X");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(numberInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numberInput, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(enterbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button
        // TODO add your handling code here:

        String inputField = numberInput.getText();  // get string from user
        int convertToInt = Integer.parseInt(inputField); // convert the string to int value

        output.setText(convert(convertToInt));  // setting the output to words after converting
//         System.out.println(convert(convertToInt)); // to show words on my terminal
    }//GEN-LAST:event_button

    private void outputclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputclick
        // TODO add your handling code here:
        numberInput.setText("Enter a number"); // set input field placeholder when output is clicked
        output.setEditable(false);  // setting output not editable when click
    }//GEN-LAST:event_outputclick

    private void bodyclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodyclick
        // TODO add your handling code here:
        numberInput.setText("Enter a number"); // if body is click set number input to my place holder

    }//GEN-LAST:event_bodyclick

    private void cancel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel
        // TODO add your handling code here:
        numberInput.setText(""); // to set my user input to an empty string
    }//GEN-LAST:event_cancel

    private void clear(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clear
        // TODO add your handling code here:
        try {
            String input = numberInput.getText();
            if (input.contains("Enter a number")) {
                numberInput.setText("");
            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_clear

    private void clear1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear1
        // TODO add your handling code here:
        output.setText("");  // to set my user output to an empty string
    }//GEN-LAST:event_clear1

    public static String convert(int convertToInt) {
        String[] belowTen = new String[]{"", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"};
        String[] belowTwenty = new String[]{"Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"};
        String[] belowHundred = new String[]{"", "Ten", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"};

        String words = "";  // storing the words picked from the array here and later displays it

        if (convertToInt == 0) {
            words += "Zero";
        }
        if (convertToInt > 1999999999) {
            words += "Number should not exceed 2billion";
        }

        if (convertToInt < 10) {
            words += belowTen[convertToInt];
        } else if (convertToInt < 20) {
            words += belowTwenty[convertToInt - 10];
        } else if (convertToInt < 100) {
            words += belowHundred[convertToInt / 10] + " " + belowTen[convertToInt % 10];
        } else if (convertToInt < 1000) {
            words += convert(convertToInt / 100) + " Hundred " + convert(convertToInt % 100);
        } else if (convertToInt < 1000000) {
            words += convert(convertToInt / 1000) + " Thousand " + convert(convertToInt % 1000);
        } else if (convertToInt < 1000000000) {
            words += convert(convertToInt / 1000000) + " Million " + convert(convertToInt % 1000000);
        } else if (convertToInt < 2000000000) {
            words += convert(convertToInt / 1000000000) + " Billion " + convert(convertToInt % 1000000000);
        }

        return words;  // return words that have been stored in words variable
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Number_to_words.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Number_to_words.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Number_to_words.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Number_to_words.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Number_to_words().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JLabel cancel;
    private javax.swing.JButton enterbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numberInput;
    private javax.swing.JTextArea output;
    // End of variables declaration//GEN-END:variables
}
